### PR TITLE
hey I added a cool box background and other things...

### PR DESCRIPTION
**Pull request by moebiussurfing**
check if you like, and feel free to merge if desired. 
thanks for your addons. cheers

### CODE REVIEW

**Comment by tettou771** [comment]
I'm grad you upgraded the addon!
It has compatibility my version, and more powerful. I like it.
So I pulled it.
Thanks!

**Comment by moebiussurfing** [comment]
nice you like it!
Check this one too:
https://github.com/moebiussurfing/ofxHelpMessage
Maybe I can rename or better to create a new addon as is different purpose than "just show help".

**Comment by tettou771** [comment]
I checked ofxHelpMessage. It's very good debug tool!
I think it should have more good name, too. I wanna use your addon and my addon(to just show help) both.

**Comment by moebiussurfing** [comment]
cool! thanks. then I'll split ofxHelpMessage to another addon with another name.

ps:
I have seen some nice addons to handle keys callbacks easily.
Your ofxHelpMessage it remembers me to them, as a complement/mix them may be...
https://github.com/thomasgeissl/ofxKeyMapper
https://github.com/2bbb/ofxKeyEvent
Sometimes is very tedious to add keys to keyPressed(ofKeyEventArgs &eventArgs)

**Pull request merged**
